[changelog]
header = """
# Changelog

All notable changes to this project will be automatically documented in this file.
"""
body = """
{%- macro remote_url() -%}
  https://github.com/usemarbles/langmail
{%- endmacro -%}

{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}**{{ commit.scope }}**: {% endif %}{{ commit.message | upper_first }}\
          {% if commit.breaking %} [**BREAKING**]{% endif %}\
          ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))\
    {%- endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
protect_breaking_commits = true
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactor" },
    { message = "^test", skip = true },
    { message = "^doc|^docs", skip = true },
    { message = "^ci", skip = true },
    { message = "^build", skip = true },
    { message = "^ops", skip = true },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore: release", skip = true },
    { message = "^chore|^style", skip = true },
    { message = "^Merge", skip = true },
]
filter_commits = true
tag_pattern = "v[0-9].*"
sort_commits = "newest"
include_merge_commit_parents = true
