/* auto-generated by NAPI-RS — do not edit manually */
/* eslint-disable */

export interface NapiAddress {
  /** Display name (e.g. "Alice"). */
  name?: string | null;
  /** Email address (e.g. "alice@example.com"). */
  email: string;
}

export interface EmailOutput {
  /** The cleaned email body text, with quotes and signature removed. */
  body: string;
  /** Email subject line. */
  subject?: string | null;
  /** Sender address. */
  from?: NapiAddress | null;
  /** Recipient addresses. */
  to: NapiAddress[];
  /** CC addresses. */
  cc: NapiAddress[];
  /** Date as ISO 8601 string. */
  date?: string | null;
  /** Message-ID header value. */
  messageId?: string | null;
  /** In-Reply-To header values (for threading). */
  inReplyTo?: string[] | null;
  /** References header values (for threading). */
  references?: string[] | null;
  /** Extracted signature, if found. */
  signature?: string | null;
  /** Length of the original body before cleaning. */
  rawBodyLength: number;
  /** Length of the cleaned body. */
  cleanBodyLength: number;
}

export interface PreprocessOptions {
  /** Whether to strip quoted reply content. Default: true. */
  stripQuotes?: boolean;
  /** Whether to strip email signatures. Default: true. */
  stripSignature?: boolean;
  /** Maximum body length in characters. 0 = no limit. Default: 0. */
  maxBodyLength?: number;
}

/**
 * Preprocess a raw email into an LLM-ready structure.
 *
 * Accepts raw email bytes (RFC 5322 / EML format) and returns a structured
 * object with clean body text and metadata.
 */
export function preprocess(raw: Buffer): EmailOutput;

/**
 * Preprocess a raw email with custom options.
 */
export function preprocessWithOptions(
  raw: Buffer,
  options: PreprocessOptions
): EmailOutput;

/**
 * Preprocess a raw email string (convenience wrapper).
 * Same as `preprocess` but accepts a string instead of a Buffer.
 */
export function preprocessString(raw: string): EmailOutput;
