/* auto-generated by NAPI-RS */
/* eslint-disable */
/** An email address with optional display name. */
export interface NapiAddress {
  /** Display name (e.g. "Alice"). */
  name?: string
  /** Email address (e.g. "alice@example.com"). */
  email: string
}

/** A primary call-to-action link extracted from an HTML email. */
export interface NapiCallToAction {
  /** The URL the action points to. */
  url: string
  /** Human-readable label for the action. */
  text: string
  /** Confidence score between 0.0 and 1.0. */
  confidence: number
}

/** Options for `toLlmContextWithOptions`. */
export interface NapiLlmContextOptions {
  /** How to render the email body. Default: "LatestOnly". */
  renderMode?: NapiRenderMode
}

/** Controls how `toLlmContextWithOptions` renders the email body. */
export declare const enum NapiRenderMode {
  /** Strip all quoted content — only the latest message is rendered. */
  LatestOnly = 'LatestOnly',
  /** Render quoted replies as a chronological transcript below the main content. */
  ThreadHistory = 'ThreadHistory'
}

/** A single message extracted from a quoted reply chain. */
export interface NapiThreadMessage {
  /** The sender attribution (e.g. "Max Mustermann <test@example.com>"). */
  sender: string
  /** ISO 8601 timestamp, if parseable from the attribution. */
  timestamp?: string
  /** The message body (cleaned, no nested quotes). */
  body: string
}

/**
 * Preprocess a raw email into an LLM-ready structure.
 *
 * Accepts raw email bytes (RFC 5322 / EML format) and returns a structured
 * object with clean body text and metadata.
 *
 * @param raw - Raw email as a Buffer or Uint8Array
 * @returns Preprocessed email output
 */
export declare function preprocess(raw: Buffer): ProcessedEmail

/** Options for customizing preprocessing behavior. */
export interface PreprocessOptions {
  /** Whether to strip quoted reply content. Default: true. */
  stripQuotes?: boolean
  /** Whether to strip email signatures. Default: true. */
  stripSignature?: boolean
  /** Maximum body length in characters. 0 = no limit. Default: 0. */
  maxBodyLength?: number
}

/**
 * Preprocess a raw email string (convenience wrapper).
 *
 * Same as `preprocess` but accepts a string instead of a Buffer.
 *
 * @param raw - Raw email as a string
 * @returns Preprocessed email output
 */
export declare function preprocessString(raw: string): ProcessedEmail

/**
 * Preprocess a raw email with custom options.
 *
 * @param raw - Raw email as a Buffer or Uint8Array
 * @param options - Preprocessing options
 * @returns Preprocessed email output
 */
export declare function preprocessWithOptions(raw: Buffer, options: PreprocessOptions): ProcessedEmail

/** Preprocessed email output optimized for LLM consumption. */
export interface ProcessedEmail {
  /** The cleaned email body text, with quotes and signature removed. */
  body: string
  /** Email subject line. */
  subject?: string
  /** Sender address. */
  from?: NapiAddress
  /** Recipient addresses. */
  to: Array<NapiAddress>
  /** CC addresses. */
  cc: Array<NapiAddress>
  /** Date as ISO 8601 string. */
  date?: string
  /** RFC 2822 Message-ID header value. */
  rfcMessageId?: string
  /** In-Reply-To header values (for threading). */
  inReplyTo?: Array<string>
  /** References header values (for threading). */
  references?: Array<string>
  /** Extracted signature, if found. */
  signature?: string
  /** Length of the original body before cleaning. */
  rawBodyLength: number
  /** Length of the cleaned body. */
  cleanBodyLength: number
  /** Primary call-to-action link extracted from the HTML body, if any. */
  primaryCta?: NapiCallToAction
  /** Thread messages extracted from quoted reply blocks (oldest first). */
  threadMessages: Array<NapiThreadMessage>
}

/**
 * Format a preprocessed email as an LLM-ready context string.
 *
 * Takes a `ProcessedEmail` (as returned by `preprocess`) and returns a
 * deterministic plain-text representation with header lines followed by a
 * CONTENT section, suitable for pasting into an LLM prompt.
 *
 * @param email - A ProcessedEmail object
 * @returns Formatted context string
 */
export declare function toLlmContext(email: ProcessedEmail): string

/**
 * Format a preprocessed email as an LLM-ready context string with options.
 *
 * Same as `toLlmContext` but accepts options to control rendering, e.g.
 * `{ renderMode: "ThreadHistory" }` to include quoted reply history.
 *
 * @param email - A ProcessedEmail object
 * @param options - LLM context options
 * @returns Formatted context string
 */
export declare function toLlmContextWithOptions(email: ProcessedEmail, options: NapiLlmContextOptions): string
