/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Preprocessed email output optimized for LLM consumption. */
export interface EmailOutput {
  /** The cleaned email body text, with quotes and signature removed. */
  body: string
  /** Email subject line. */
  subject?: string
  /** Sender address. */
  from?: NapiAddress
  /** Recipient addresses. */
  to: Array<NapiAddress>
  /** CC addresses. */
  cc: Array<NapiAddress>
  /** Date as ISO 8601 string. */
  date?: string
  /** Message-ID header value. */
  messageId?: string
  /** In-Reply-To header values (for threading). */
  inReplyTo?: Array<string>
  /** References header values (for threading). */
  references?: Array<string>
  /** Extracted signature, if found. */
  signature?: string
  /** Length of the original body before cleaning. */
  rawBodyLength: number
  /** Length of the cleaned body. */
  cleanBodyLength: number
}
/** An email address with optional display name. */
export interface NapiAddress {
  /** Display name (e.g. "Alice"). */
  name?: string
  /** Email address (e.g. "alice@example.com"). */
  email: string
}
/** Options for customizing preprocessing behavior. */
export interface PreprocessOptions {
  /** Whether to strip quoted reply content. Default: true. */
  stripQuotes?: boolean
  /** Whether to strip email signatures. Default: true. */
  stripSignature?: boolean
  /** Maximum body length in characters. 0 = no limit. Default: 0. */
  maxBodyLength?: number
}
/**
 * Preprocess a raw email into an LLM-ready structure.
 *
 * Accepts raw email bytes (RFC 5322 / EML format) and returns a structured
 * object with clean body text and metadata.
 *
 * @param raw - Raw email as a Buffer or Uint8Array
 * @returns Preprocessed email output
 */
export declare function preprocess(raw: Buffer): EmailOutput
/**
 * Preprocess a raw email with custom options.
 *
 * @param raw - Raw email as a Buffer or Uint8Array
 * @param options - Preprocessing options
 * @returns Preprocessed email output
 */
export declare function preprocessWithOptions(raw: Buffer, options: PreprocessOptions): EmailOutput
/**
 * Preprocess a raw email string (convenience wrapper).
 *
 * Same as `preprocess` but accepts a string instead of a Buffer.
 *
 * @param raw - Raw email as a string
 * @returns Preprocessed email output
 */
export declare function preprocessString(raw: string): EmailOutput
